'use client';
import Image from 'next/image';
import Link from 'next/link';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Catalog, Filters, Product } from '../lib/types';
import { filterProducts, exportCSV, matchesQuery } from '../lib/catalog.mjs';
import { asset, documentURL, number, modelPath } from '../lib/format';
import { Icon } from './icon';
import { PriceSummary } from './calculated-prices';
import { SaveButton, useSaved } from './workspace';
const categories=['Door handles','Sofa legs','Knobs','Profile handles','Concealed handles','Brackets'];
const statuses=[['','All records'],['priced','With prices'],['unpriced','Price not listed'],['notes','With source notes'],['no-picture','Picture not available']];
function initial(params:URLSearchParams,view:Filters['view']):Filters{return {view,query:params.get('q')||'',category:categories.includes(params.get('category')||'')?params.get('category')!:'',size:params.get('size')||'',finish:params.get('finish')||'',status:params.get('status')||'',sort:params.get('sort')||'model',layout:params.get('layout')==='list'?'list':'grid'};}
export function Library({catalog,view}:{catalog:Catalog;view:Filters['view']}){
 const searchParams=useSearchParams();const pathname=usePathname();const router=useRouter();const {saved}=useSaved();
 const state=initial(new URLSearchParams(searchParams.toString()),view);
 const searchRef=useRef<HTMLInputElement>(null);const [toast,setToast]=useState('');
 const docs=view==='documents',isSaved=view==='saved';
 const title=docs?'Source documents':isSaved?'Your shortlist':'Product library';
 const update=(patch:Partial<Filters>)=>{
  const next={...state,...patch};const params=new URLSearchParams();
  for(const [key,value] of Object.entries({q:next.query,category:next.category,size:next.size,finish:next.finish,status:next.status,sort:next.sort==='model'?'':next.sort,layout:next.layout==='grid'?'':next.layout}))if(value)params.set(key,String(value));
  window.history.replaceState(null,'',pathname+(params.size?'?'+params.toString():''));
 };
 const reset=()=>update({query:'',category:'',size:'',finish:'',status:'',sort:'model'});
 useEffect(()=>{const legacy=searchParams.get('product');if(legacy&&catalog.products.some(p=>p.id===legacy))router.replace(modelPath(legacy));else if(pathname==='/'&&searchParams.get('view')==='documents')router.replace('/documents');else if(pathname==='/'&&searchParams.get('view')==='saved')router.replace('/shortlist');},[searchParams,router,catalog.products,pathname]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement).tagName)&&!e.ctrlKey&&!e.metaKey){e.preventDefault();searchRef.current?.focus();}};document.addEventListener('keydown',handler);return ()=>document.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3000);return ()=>clearTimeout(timer);},[toast]);
 const sizes=useMemo(()=>[...new Set(catalog.products.flatMap(p=>p.sizes.flatMap(s=>{const range=s.match(/^(\d+)[–-](\d+) in$/);return range?Array.from({length:Number(range[2])-Number(range[1])+1},(_,i)=>(Number(range[1])+i)+' in'):/^\d+ in$/.test(s)?[s]:[];})))].sort((a,b)=>parseInt(a)-parseInt(b)),[catalog.products]);
 const results=filterProducts(catalog.products,state,saved) as Product[];
 const pages=docs&&state.query.trim()?catalog.pages.filter(p=>matchesQuery(p.text+' '+catalog.documents.find(d=>d.id===p.document)?.title,state.query)):[];
 const priced=catalog.products.filter(p=>p.minPrice!==null).length;
 const entries=catalog.products.reduce((sum,p)=>sum+p.variants.reduce((n,v)=>n+Object.values(v.prices).filter(x=>x!==null).length,0),0);
 const exportResults=()=>{const blob=new Blob([exportCSV(results,catalog.documents)],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='dalmia-products.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setToast(`Exported ${results.length} ${results.length===1?'product':'products'} with price rows.`);};
 const filters=(['category','size','finish','status'] as const).filter(k=>state[k]);
 return <>
 <div className="heading"><div><p className="eyebrow">THE DALMIA COLLECTION</p><h1>{title}</h1><p className="subtitle">{docs?'Your original catalogs and price lists, with every page searchable.':isSaved?'A place for the models you want to come back to.':'Find the right model. Every detail, at your fingertips.'}</p></div>{!docs&&<button id="export" className="button" disabled={!results.length} onClick={exportResults}><Icon name="download"/>Export results</button>}</div>
 <div className="stats" aria-label="Collection overview">{[{icon:'grid',value:catalog.products.length,label:'Products in your library',note:'6 categories'},{icon:'tag',value:priced,label:'Models with listed prices',note:`${number(entries)} price entries`},{icon:'folder',value:catalog.documents.length,label:'Original documents',note:`${catalog.pages.length} pages indexed`}].map(s=><div className="stat" key={s.icon}><span className="stat-icon"><Icon name={s.icon}/></span><div><strong>{s.value}</strong><p>{s.label}</p></div><small>{s.note}</small></div>)}</div>
 <div className="searchbar"><Icon name="search"/><label className="sr-only" htmlFor="search">Search models and product details</label><input ref={searchRef} type="search" id="search" value={state.query} onChange={e=>update({query:e.target.value})} placeholder={docs?'Search document text, model numbers, terms, or specifications…':'Search by model number, finish, size, or keyword…'} autoComplete="off"/>{state.query&&<button aria-label="Clear search" onClick={()=>{update({query:''});searchRef.current?.focus();}}><Icon name="x"/></button>}<kbd>/</kbd></div>
 {!docs&&<><div className="categories" aria-label="Product categories">{['',...categories].map(c=><button className={'category '+(state.category===c?'active':'')} key={c} aria-pressed={state.category===c} onClick={()=>update({category:c})}>{c||'All products'}<span>{catalog.products.filter(p=>(!c||p.category===c)&&(!isSaved||saved.has(p.id))).length}</span></button>)}</div><div className="toolbar"><p id="result-count" role="status" aria-live="polite"><strong>{results.length}</strong> {results.length===1?'product':'products'}{state.query?' found':' in your '+(isSaved?'shortlist':'library')}</p><div className="filter-group"><label className="sr-only" htmlFor="size">Size</label><select id="size" value={state.size} onChange={e=>update({size:e.target.value})}><option value="">All sizes</option>{sizes.map(s=><option key={s}>{s}</option>)}</select><label className="sr-only" htmlFor="finish">Finish</label><select id="finish" value={state.finish} onChange={e=>update({finish:e.target.value})}><option value="">All finishes</option>{['Black','Gold','Rosegold','CP','Matt','Antique','Green','Grey'].map(s=><option key={s}>{s}</option>)}</select><label className="sr-only" htmlFor="status">Data availability</label><select id="status" value={state.status} onChange={e=>update({status:e.target.value})}>{statuses.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select><label className="sr-only" htmlFor="sort">Sort products</label><select id="sort" value={state.sort} onChange={e=>update({sort:e.target.value})}><option value="model">Model number</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select><div className="view-toggle" aria-label="Result layout">{['grid','list'].map(layout=><button key={layout} id={layout+'-view'} className={state.layout===layout?'selected':''} aria-label={layout==='grid'?'Grid view':'List view'} aria-pressed={state.layout===layout} onClick={()=>update({layout})}><Icon name={layout}/></button>)}</div></div></div>{!!filters.length&&<div className="active-filters">{filters.map(k=><button className="chip" key={k} onClick={()=>update({[k]:''})}>{k==='status'?statuses.find(s=>s[0]===state[k])?.[1]:state[k]}<Icon name="x"/></button>)}<button className="text-button" onClick={reset}>Reset filters</button></div>}</>}
 {docs?<>
 <p className="document-count" role="status">{state.query.trim()?`${pages.length} matching ${pages.length===1?'page':'pages'} · Scanned pages use machine-read text.`:`${catalog.documents.length} documents · ${catalog.pages.length} pages · Original files preserved`}</p>
 <div className="product-grid documents-grid">{!state.query.trim()?<>{catalog.documents.map(d=><article className="document-card" key={d.id}><a href={documentURL(catalog.documents,d.id)} target="_blank" rel="noopener" aria-label={`Open ${d.title} PDF`}><div className="document-cover"><Image src={asset(`assets/pages/${d.id}-01.jpg`)} alt={`Cover of ${d.title}`} width={612} height={828} sizes="(max-width:620px) 90vw, 30vw"/></div></a><div className="document-body"><span className="card-category">{d.kind}</span><h2 className="card-title">{d.title}</h2><p>{d.pages} pages <span className="dot">·</span> {(d.bytes/1024/1024).toFixed(1)} MB<br/>{d.file}</p><div className="document-actions"><a className="button" href={documentURL(catalog.documents,d.id)} target="_blank" rel="noopener">Open PDF <Icon name="arrowUpRight"/></a><a className="button" href={documentURL(catalog.documents,d.id)+'?download'} download aria-label={`Download ${d.file}`}><Icon name="download"/></a></div></div></article>)}<section className="document-terms"><h2>Notes from the price lists</h2><p>{catalog.priceNote}</p><details><summary>Read the original terms and conditions</summary><pre>{catalog.terms}</pre><a className="button" href={documentURL(catalog.documents,'sofa-prices',8)} target="_blank" rel="noopener">View source <Icon name="arrowUpRight"/></a></details></section></>:pages.length?pages.map(p=>{const d=catalog.documents.find(d=>d.id===p.document)!;const index=Math.max(0,p.text.toLowerCase().indexOf(state.query.toLowerCase().split(/\s+/)[0])-70);return <article className="document-result" key={p.document+p.page}><Image src={asset(p.image)} alt={`Page ${p.page}`} width={72} height={94}/><div><h2>{d.title} · Page {p.page}</h2><p>{index?'…':''}{p.text.slice(index,index+280).replace(/\s+/g,' ')}…</p></div><a className="button" href={documentURL(catalog.documents,p.document,p.page)} target="_blank" rel="noopener">Open page <Icon name="arrowUpRight"/></a></article>}):<div className="empty"><h2>No matching pages</h2><p>Try a model number, material, finish, or a shorter phrase.</p><button className="button" onClick={reset}>Clear search</button></div>}</div>
 </>:<div id="results" className={'product-grid'+(state.layout==='list'?' list':'')}>{results.length?results.map((p,i)=><ProductCard key={p.id} product={p} eager={i<4}/>):<div className="empty"><Icon name={isSaved?'bookmark':'search'}/><h2>{isSaved&&!saved.size?'Keep your favorites close.':'No matching products'}</h2><p>{isSaved&&!saved.size?'Use the bookmark on a product to add it to your shortlist.':'Try a model number such as 1701, or remove a filter.'}</p>{isSaved&&!saved.size?<Link className="button" href="/">Browse the library</Link>:<button className="button" onClick={reset}>Clear search and filters</button>}</div>}</div>}
 {toast&&<div role="status" className="toast">{toast}</div>}
 </>;
}
function ProductCard({product:p,eager}:{product:Product;eager:boolean}){const img=p.images[0];const perInch=p.variants.some(v=>v.unit==='Per inch');const sizes=p.sizes.filter(s=>s!=='Not specified');return <article className="product-card"><SaveButton id={p.id} model={p.model} category={p.category} compact/><Link className="card-open" href={modelPath(p.id)} aria-label={`View ${p.category} ${p.model}`}><div className="product-photo">{img?<Image src={asset(img.src)} alt={`${p.category} ${p.model}`} width={img.width} height={img.height} sizes="(max-width:620px) 45vw, (max-width:1200px) 28vw, 22vw" loading={eager?'eager':'lazy'}/>:<div className="image-missing"><Icon name="image"/><span>No matching catalog picture</span></div>}</div>{!!p.notes.length&&<span className="data-note">Source note</span>}<div className="card-body"><span className="card-category">{p.category}</span><h2 className={'card-title '+(p.model.length>12?'long':'')}>{p.model}</h2><p className="card-description">{sizes.length?`${sizes.length} ${perInch?'size ranges':'sizes'}`:'See catalog details'} <span className="dot">·</span> {p.variants.length?`${p.variants.length} price ${p.variants.length===1?'row':'rows'}`:'Catalog only'}</p><div className="card-bottom"><div className="price"><small>{p.minPrice===null?'Price':p.minPrice===p.maxPrice?'Listed price':'Starting at'}</small><strong>{p.minPrice===null?'Not listed':number(p.minPrice)}</strong>{perInch&&<em>/ inch</em>}</div><span className="card-arrow"><Icon name="arrowRight"/></span></div><PriceSummary product={p}/></div></Link></article>;}
