import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const source=path.resolve(process.argv[2] || path.join(root,'../web-app'));
const catalog=JSON.parse(await readFile(path.join(source,'data/catalog.json'),'utf8'));
await mkdir(path.join(root,'assets/products'),{recursive:true});
await mkdir(path.join(root,'src/data'),{recursive:true});
const images=[];
for(const product of catalog.products){
 const image=product.images[0];
 if(!image)continue;
 const filename=path.basename(image.src);
 await copyFile(path.join(source,'public',image.src),path.join(root,'assets/products',filename));
 images.push(`  ${JSON.stringify(product.id)}: require(${JSON.stringify('../../assets/products/'+filename)}),`);
}
await writeFile(path.join(root,'src/data/images.ts'),`// Generated by scripts/sync-catalog.mjs.\nexport const productImages: Record<string, number> = {\n${images.join('\n')}\n};\n`);
const products=catalog.products.map(({catalogText,...product})=>product);
await writeFile(path.join(root,'src/data/catalog.json'),JSON.stringify({products,documents:catalog.documents,priceNote:catalog.priceNote},null,2)+'\n');
await copyFile(path.join(source,'lib/catalog-api.mjs'),path.join(root,'src/lib/catalog-api.mjs'));
await copyFile(path.join(source,'lib/pricing.mjs'),path.join(root,'src/lib/pricing.mjs'));
await copyFile(path.join(source,'lib/types.ts'),path.join(root,'src/types.ts'));
const logo=await readFile(path.join(source,'public/assets/dalmia-wordmark.svg'),'utf8');
const mark=await readFile(path.join(source,'public/assets/dalmia-monogram.svg'),'utf8');
await writeFile(path.join(root,'src/data/brand.ts'),`// Original vector artwork from the supplied Dalmia brochure.\nexport const wordmark=${JSON.stringify(logo)};\nexport const monogram=${JSON.stringify(mark)};\n`);
console.log(`Bundled ${products.length} products and ${images.length} separate images for offline use.`);
